python3 -m train \
	--data_path ../data/Neurology \
	--log_path ./logs/Neu_TSIE \
	--model_save_path ./Models/Neu_TSIE \
	--device cuda:0 \
	--model TSIE \
	--agg_type gcn \
	--backbone Sage \
	--test_type full \
	--batch_size 2048 \
	--nhead 2 \
	--num_layers 1 \
	--nhead_2 2 \
	--num_layers_2 1 \
	--dropout_trans 0.3 \
	--input_dim 300 \
	--hidden_dim 256 \
	--output_dim 1 \
	--learning_rate 5e-4 \
	--dropout_rate 0.3 \
	--epoch 10 \
	--sample_size_1 -1 \
	--sample_size_2 -1 \
	--rnn_wnd 5 \
	--attn_wnd 5 \
	--year_start 1950 \
	--year_end 2010 \
	--year_interval 10